### ISSUE TITLE
The Windows desktop version of ruffle works terribly

### ISSUE THREAD

**Issue by WingFoxie** [ruffle-rs/ruffle#2065]
I tried two versions of ruffle, the "https://ruffle.rs/demo/" version (using Firefox), and the "ruffle_nightly_2020_xx_xx_windows.zip" version. The Windows version is terrible in many ways.

First, I'll report the most frustrating thing: Memory leak. The Windows version could use like 30% RAM (I have 16GB RAM) when opening a swf file. while using the web demo, it only uses about 0.1%. 
Sometimes the Windows version will even use 50% RAM and climbing, making my whole system freeze for a while, before it finally crashes.
This made me too scared to even test the Windows version more!

Second, I have difficulties setting up the player. 
I expect to just double click a .swf file, and Windows will automatically open it with "ruffle.exe". (Just like what I did with "flashplayer_25_sa_debug.exe".)
But that won't open correctly. I can't open any swf file directly with ruffle.exe.
I need a launch parameter "--graphics dx12". But then how do I config Windows to automatically add that launch parameter? There's no way I can do that.

I ended up creating a shortcut of "ruffle.exe", adding the launch parameter in the shortcut's properties. To open any file, I have to drag the swf file to the shortcut, to open it.

What should happen is that, ruffle.exe reads a "settings.ini" file when it launches. So I can set the launch parameters in that ".ini" file.
And if there's no "settings.ini" file, create one with default settings. (Don't just include a ini file in the release zips, so updating Ruffle won't overwrite the existing ini file and reset settings.)

Meanwhile...
The web demo version works fine. Just like the adobe flash player (lot of swf files I tested didn't work correctly, of course, but at least no serious problems, no freezing my system, no 70% RAM usage, and most swf files will at least show a first screen correctly).

(Before you ask, I tested Ruffle desktop version on 3 different nightly builds, during this time period I upgraded my graphics driver twice. So I can confirm this is a persistent problem.)

**Comment by ZingBallyhoo** [comment]
Have you tried using the vulkan backend for rendering? For me its the default and works way better but you may need to choose it with `-g vulkan`.

There's defintely something wrong with both DX backends, playing anything substantial (e.g Achievement Unlocked) with either causes insane leaks.
![image](https://user-images.githubusercontent.com/13888932/102896226-f0f27180-445d-11eb-98b3-553098d1688d.png)

**Comment by WingFoxie** [comment]
> 
> 
> Have you tried using the vulkan backend for rendering? For me its the default and works way better but you may need to choose it with `-g vulkan`.
> 
> There's defintely something wrong with both DX backends, playing anything substantial (e.g Achievement Unlocked) with either causes insane leaks.
> ![image](https://user-images.githubusercontent.com/13888932/102896226-f0f27180-445d-11eb-98b3-553098d1688d.png)

1. **Vulcan is NOT working for me.** I have to use dx12 to get anything to work, I can't make ruffle load anything if I use vulcan.

2. **Why do you say "-g vulcan" instead of "--graphics vulcan"??** There should be an extra "-". For example. I tried to use dx12 by using "-g dx12", but it WON'T work! This confused me quite a while, until I realized I should use "--graphics dx12" instead.
And I saw this "-g dx12" thing in another post, which means someone else's used this to set ruffle to dx12 mode, but it just won't work for me! Only "--graphics dx12" works.
(For the vulcan thing, I tried both "-g vulcan" and "--graphics vulcan", won't work, ruffle will just crash after a few seconds.)

3. I wonder why the web demo works perfectly? The web demo and the desktop version, are supposed to, eventually, use my CPU and GPU in the same way, right...>

**Comment by ZingBallyhoo** [comment]
Not sure if its just a typing issue, but please make sure you are using `vulkan` and not `vulcan`. Does it report an error when you try this?

r.e -g vs --graphics: both should work

**Comment by WingFoxie** [comment]
> 
> 
> Not sure if its just a typing issue, but please make sure you are using `vulkan` and not `vulcan`. Does it report an error when you try this?
> 
> r.e -g vs --graphics: both should work

1. Sorry for the typo in my post. But it was only in the post. I tried these again, here are the results:

"-g dx12" works, just with the memory leak problem.
"--graphics dx12" works, just with the memory leak problem.

"-g vulkan" won't work, ruffle will just pop up a white blank screen and exit after a moment.
"--graphics vulkan" won't work, ruffle will just pop up a white blank screen and exit after a moment.
No launch parameters---won't work, ruffle will just pop up a white blank screen and exit after a moment.

2. "Does it report an error"? What error? The app just pops up for a split second and exits.
I guess you mean to open command prompt first, run "ruffle.exe" and open a swf file? when I do that I got this:

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.6.5\src\lib.rs:1529:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is what I got, by using the command "ruffle". If I use the command "ruffle -g vulkan", I got the exact same thing.
(If I use command "ruffle -g dx12", it works without error just memory leaks)

(I'm aware there's a "note" in the output, but I don't know what to do with it.)

**Comment by Herschel** [comment]
The issue with Vulkan hanging is probably #1799.

**Comment by ZingBallyhoo** [comment]
@Herschel r.e memory issues

[Achievement Unlocked](https://uploads.ungrounded.net/474000/474371_achievementunlocked_public.swf?123)

| Backend| Description | Graph |
| --- | --- | --- |
| Vulkan | preloader starts at 180mb, grows to 210mb after a couple of minutes. Going ingame increases usage to 250mb | ![image](https://user-images.githubusercontent.com/13888932/102989722-01fabb80-450e-11eb-9c11-512a2e0c57a6.png) |
| DX11 | preloader starts at about 450mb and grows ~1mb/sec. Going ingame increases usage to 3GB which continues to grow. | ![image](https://user-images.githubusercontent.com/13888932/102988751-5309b000-450c-11eb-9bdd-34d926d72371.png) |
| DX12 | preloader very slowly increases from about 500mb. Going ingame increases usage to 1.3GB which continues to grow. | ![image](https://user-images.githubusercontent.com/13888932/102989207-21451900-450d-11eb-967e-0094b04c2ce4.png) |

[Not a playable game (AS3), but I think its a pretty good example here because it really causes issues](https://cdn.binw.net/core.swf)

| Backend| Description | Graph |
| --- | --- | --- |
| Vulkan | starts at about 250mb and increases 10-30mb / second| ![image](https://user-images.githubusercontent.com/13888932/102990367-2905bd00-450f-11eb-9f91-624251371b06.png) |
| DX11 | usage instantly climbs to >5GB. Process hacker reports 15GB of usage after about a minute | ![image](https://user-images.githubusercontent.com/13888932/102990551-784bed80-450f-11eb-9d28-870a42869e1c.png) |
| DX12 | usage starts at 2GB and climbs about 5mb/sec maybe? | ![image](https://user-images.githubusercontent.com/13888932/102990752-d4167680-450f-11eb-861c-b502ebed982f.png) |

**Comment by WingFoxie** [comment]
> Could you post a link to the SWF you are trying to play so that we can look into the memory leak? 
Oh no. It's not related to any paricular SWF file.

Here's the thing, I have about 200 SWF files on my computer. And I tried quite a few of them, all have memory leak problems when loaded with Windows desktop version of Ruffle.
Even a game that I think Ruffle already has full support to: cursor10.swf, will use like 6.0% or RAM when I load it with the Windows desktop version, and use like 0.2% or RAM when I use the web demo, or use Adobe flash player.

To further prove this, I downloaded a swf file stright from "Ruffle Web Demo"! I downloaded "Alien Hominid.swf" Opened it with Ruffle.exe, RAM usage is 13% and climbing...
BTW the link is "https://ruffle.rs/demo/swfs/alien_hominid.swf" ;b

**Comment by Herschel** [comment]
Thank you! I understand it happens in most SWF files, just trying to focus on a particular one so that I can reproduce the exact behavior and verify once it is fixed.

**Comment by Herschel** [comment]
Could you try on the latest nightly? There should be some improvement with memory usage, and the Nvidia vulkan hang should be fixed. Thank you!

**Comment by WingFoxie** [comment]
Tried. Here are the results...

1. Vulkan is WORKING now. 
Now I can use both Vulkan and DX12 mode. (Seem that if I launch Ruffle without a launch parameter, it uses Vulkan by default.)

2. The memory usage, hmm...
If I use Ruffle (Vulkan mode) to open that "Alien Hominid.swf" again, RAM usage is 3.4%. as I keep playing it raises to about 4% and STAYS THERE.
Still no match for web version's 0.2%, but it's good enough for me.
However, if I use DX12 mode, things are not looking good, if I open that "Alien Hominid.swf" again, RAM usage is like 6% and climbing, about +0.1~0.2% each second. And it doesn't seem to stop climbing. (I waited until it climbs to over 15%, and closed the app.)

Tried a few other swf files, results are similar: 
Vulkan mode uses a lot of RAM (20x RAM usage than web version, can't really measure the web version's RAM usage so I'm sort of guessing) but it's manageable. 
DX12 mode is just out of control (RAM usage is higher than Vulkan mode at the beginning, and keeps climbing).

**Comment by WingFoxie** [comment]
Wait a minute, just found another problem. 
**Minimizing the Ruffle window will crash the app!**
(By "minimizing" I mean clicking the minimize button on the title bar of the window, or click the button on the taskbar.)
This crashing problem **only happens with Vulkan, not DX12.**

**Comment by WingFoxie** [comment]
Tried the latest release (ruffle_nightly_2020_12_30_windows.zip), and things are getting better than the last time.
Now the "Alien Hominid.swf" RAM usage is initially 2.7%, and climbs to about 3.2% as I play. (Vulkan mode, which is used by default)

DX12 mode still not looking good, RAM usage is 4% at the beginning (better than before), and keeps climbing +0.1~0.2% per second (same as before).

And, Ruffle no longer crashes when I minimize the window.

_(BTW I'm not sure how low the RAM usage "should" be with Ruffle desktop app, though. 
Adobe Flash Player can get 0.2% most of the time, but the performance is terrible on countless swf files. And it doesn't even support high DPI.
The video player I use (an app that is pretty modern and up-to-date) usually uses 1.5%~4% RAM._

**Comment by TPS** [comment]
How's performance compared to [_(closed-source)_ Wimpy FLV Player](https://www.wimpyplayer.net/products/wimpy_standalone_flv_player.html)?

**Comment by WingFoxie** [comment]
> 
> 
> How's performance compared to [_(closed-source)_ Wimpy FLV Player](https://www.wimpyplayer.net/products/wimpy_standalone_flv_player.html)?

What is this?? Is this a terrible joke or what? 

I spend 10 minutes or so to check that if you are a bot, because:
1. The player you mentioned is a "video player", but I'm talking about a "flash player" here.
2. The player you mentioned claims to support very few formats, not including SWF, and not even all common video formats (no mkv, no webm, etc).
3. The link you provided leads to a page, but when I click the download link for Windows PC, I got a 404! (Could still get the file if I go to the "downloads" page first, but come on! Seriously?)
4. Last, I tried to open a swf file with the player you mentioned, won't work, file won't be correctly rendered, I tried "Alien Hominid.swf", and it just won't work.

It's pointless to compare ruffle, or anything, to a player that basically don't work at all... It doesn't qualify as either a flash player or a video player.
Can't believe you bring up such a broken software. For a moment I even think if this is a bot seeing the keyword "video player" and starts advertising or what...

**Comment by Poopooracoocoo** [comment]
Ruffle sits at about 300 MB when playing Wasted Sky on my machine. That's quite a lot, but I haven't used Flash Player in a very long time so I don't know how it compares. 

I have quite a bit of stuff in the background. 82% of my memory is being used according to the windows task manager (mostly by Edge, which uses about 200 more MB than Chrome when in the foreground lol). I've got 8 GB of memory in this laptop.

I could definitely see the memory leaks when using the DX12 backend. I got scared so I ended it myself.
