### ISSUE TITLE
Multiple Bugs on https://armorgames.com/play/5003/arcuz

### ISSUE THREAD

**Issue by Bimbelimbim** [ruffle-rs/ruffle#3295]
1. Ingame item descriptions are in a wrong position.
![Distored_Item Description](https://user-images.githubusercontent.com/79198719/108194604-1c6ca200-7117-11eb-8de4-716c72c2b313.PNG)
2. Enemies do not have their correct sprites. Their sprits should change with their level, but they do not.
![Level_1_ _Level_5_Slimes_on_Ruffle](https://user-images.githubusercontent.com/79198719/108195425-06abac80-7118-11eb-8367-42e6faec01fc.PNG)
![green_Level_1_ _yellow_Level_5_Slimes_on_Flash](https://user-images.githubusercontent.com/79198719/108195426-07dcd980-7118-11eb-9103-f1f992e8f340.PNG)
3. Ruffle starts to lag extremely a few seconds after a skill is used, i only tested this with Hurricane, because without skills the game is not appealing to play, i did not progress to futher skills. Save and quitting the game (ingame menu) solves this, but that isnt a working solution of course.
![Hurricane_Skill](https://user-images.githubusercontent.com/79198719/108195896-be40be80-7118-11eb-95c3-b386d5ec2e6a.PNG)
4. None of the bugs, that were in the original game are emulated correctly, as far as i could test it, but is actually a good thing.

**Comment by adrian17** [comment]
Issue (1) was fixed with https://github.com/ruffle-rs/ruffle/pull/3163 . There are still minor margin-related issues that cause text to be just slightly cut off.

Not sure about issue (2), might be related to not-yet-implemented bitmap stuff.

Issue (3) was significantly improved with recent optimizations, but the major increasing-over-time lag still remains. I found out it's the same core issue as https://github.com/ruffle-rs/ruffle/issues/993#issuecomment-675182938 - the game creates and destroys shadows that are stored in a `layerArr` array. After the shadow is destroyed with `removeMovieClip`, normally it'd be removed from the list in `refreshLayerArray`, but the issue causes the script to not realize the movie clip is dead, so it remains in the list. This list is regularly sorted with a bubble sort, which means the sorting time increases quadratically over time :(

**Comment by Bimbelimbim** [comment]
Ive found an other problem: When I hit an enemy, this causes his health bar to be displayed till he either dies, or i stop hitting him for a few seconds. Thats how its supposed to work and how it does work, EXCEPT it only displays the health bar once the first time i attack each enemy. If i retreat and then start attacking the again the health bar doesnt reappear.

The recent ruffle updates have now also removed Issue (4) except for a small visual difference during item duping.

**Comment by Bimbelimbim** [comment]
Ive recently heared a few reports from others, that certain quests are incompleteable, a main quest among them, leaving the game impossible to complete. I concerns the "flickering iron ore" side quest and the "save anna" main quest.

**Comment by Bimbelimbim** [comment]
Ive made a savefile to doublecheck the 2 quests, they are indeed bugged. Ive recorded that. as well as all other bugs i found,
including, but not limited to the aforementioned and uploaded it to my youtube: https://youtu.be/CWqR6aKu_uw
I can share the savefile for testing with any developer interested, contact me on Discord.

**Comment by adrian17** [comment]
Just from watching, I'd guess that most of these (including quest locks) are related to the "ghost removed movieclips" FP behavior we're missing, same as above.

**Comment by Bimbelimbim** [comment]
18 month later its about time for a little update on the game. During this time I've learned a lot about the games code. The ColorMatrixFilter that the games uses to recolor enemies based on their level havent been implemented into ruffle yet, but Dinnerbone recently told me on Discord that he was working on it, which means that issue will so be fixed. The original glitches of the game have been correctly operational for quite some time and the item descriptions have also been fixed since I last commented here. 
This only leaves the "ghost removed movie" clip issue, which as has been shown in the video and explained here, causes a variety of errors ingame, including rendering it incompleteable.

**Comment by Lord-McSweeney** [comment]
This issue should be fixed by #9243, which implemented `ColorMatrixFilter`.

**Comment by HaimZik** [comment]
The game is still slowed down after using skill multiple times.
ColorMatrixFilter is unimplemented.
The treasure chests collider still remain after the chest disappear.

**Comment by n0samu** [comment]
The skill icon snapping issue is a regression caused by #7624.

**Comment by Bimbelimbim** [comment]
As of nightly 2023_11_26 only two minor issues remain in this game:

The typesetting of item descriptions ingame is left aligned in ruffle, when it is supposed to be centered.

The Item Duping (an original bug of this game) has a visual glitch where an item sprite does not show as it would in the original.

Both of these issue are minor details and do not affect gameplay. Both are also present in Arcuz 2, which is unsurprising as both games share the greater part of their code.

**Comment by Bimbelimbim** [comment]
I dipped back into ruffle and the game, in today nightly release of ruffle and while the typesetting has been fixed, item duping remains partially dysfunctional in the same way as before.
